// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/yossdev/mypoints-rest-api/src/agents/entities"

	uuid "github.com/google/uuid"
)

// PsqlRepository is an autogenerated mock type for the PsqlRepository type
type PsqlRepository struct {
	mock.Mock
}

// CreateAgent provides a mock function with given fields: payload
func (_m *PsqlRepository) CreateAgent(payload *entities.Domain) (int64, error) {
	ret := _m.Called(payload)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*entities.Domain) int64); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entities.Domain) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAgent provides a mock function with given fields: id
func (_m *PsqlRepository) GetAgent(id uuid.UUID) (entities.Domain, error) {
	ret := _m.Called(id)

	var r0 entities.Domain
	if rf, ok := ret.Get(0).(func(uuid.UUID) entities.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignInWithEmail provides a mock function with given fields: email
func (_m *PsqlRepository) SignInWithEmail(email string) (entities.Domain, error) {
	ret := _m.Called(email)

	var r0 entities.Domain
	if rf, ok := ret.Get(0).(func(string) entities.Domain); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(entities.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAgent provides a mock function with given fields: payload
func (_m *PsqlRepository) UpdateAgent(payload entities.Domain) (int64, error) {
	ret := _m.Called(payload)

	var r0 int64
	if rf, ok := ret.Get(0).(func(entities.Domain) int64); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.Domain) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAgentByAdmin provides a mock function with given fields: payload
func (_m *PsqlRepository) UpdateAgentByAdmin(payload entities.Domain) (int64, error) {
	ret := _m.Called(payload)

	var r0 int64
	if rf, ok := ret.Get(0).(func(entities.Domain) int64); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.Domain) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAvatar provides a mock function with given fields: payload
func (_m *PsqlRepository) UpdateAvatar(payload entities.Domain) (int64, error) {
	ret := _m.Called(payload)

	var r0 int64
	if rf, ok := ret.Get(0).(func(entities.Domain) int64); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.Domain) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePoints provides a mock function with given fields: id, points
func (_m *PsqlRepository) UpdatePoints(id uuid.UUID, points int32) (int64, error) {
	ret := _m.Called(id, points)

	var r0 int64
	if rf, ok := ret.Get(0).(func(uuid.UUID, int32) int64); ok {
		r0 = rf(id, points)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID, int32) error); ok {
		r1 = rf(id, points)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
