// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://swagger.io/terms/",
        "contact": {
            "name": "MyPoints Team Support",
            "email": "zenhanprogram@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/:adminId/agent": {
            "post": {
                "description": "create agent account by admins.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "admins can create agent account with this api",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "signUp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.SignUpReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.AccountCreated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/:adminId/agent/update": {
            "put": {
                "description": "update agent data by admin with agent id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "update agent data",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "updateAccount",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAgentByAdmin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.AccountUpdated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/:id/transactions/claims": {
            "post": {
                "description": "create claims transaction by agents.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "agent can create claims transaction",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "newClaims",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ClaimsReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.TransactionRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/:id/transactions/redeem": {
            "post": {
                "description": "create redeem transaction by agents.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "agent can create redeem transaction",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "newRedeem",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RedeemReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.TransactionRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/admin/:id/transactions/claims": {
            "put": {
                "description": "update claims transaction status by admins.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "admins can update claims transaction from agent",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "updateClaims",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateClaimsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TransactionRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/admin/login": {
            "post": {
                "description": "check admins by checking given email and password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "check admins by given email return jwt token if successfully signIn",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "signIn",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.SignInReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.Token"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/admin/profile/:id": {
            "put": {
                "description": "update admin data by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "update admin data",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "updateAccount",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.UpdateAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.AccountUpdated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/admin/profile/avatar/:id": {
            "put": {
                "description": "update admin photo profile by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "update admin photo profile",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "updateAvatar",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.UpdateAvatar"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.AccountUpdated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/admin/signup": {
            "post": {
                "description": "create admin account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "admins can create from register page",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "signUp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.SignUpReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.AccountCreated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "check agent by checking given email and password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "check agent by given email return jwt token if successfully signIn",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "signIn",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.SignInReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.Token"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/product/:id": {
            "post": {
                "description": "create product by admins.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "admins can create product",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "newProduct",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.NewProduct"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ProductRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/product/:id/:productId": {
            "put": {
                "description": "update product data by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "update product data",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "updateProduct",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateProduct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProductRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            },
            "delete": {
                "description": "soft delete product data by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "soft delete product data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ProductRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/profile/:id": {
            "get": {
                "description": "Get agent data by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "get agent data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Profile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            },
            "put": {
                "description": "update agent data by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "update agent data",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "updateAccount",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.UpdateAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.AccountUpdated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/profile/avatar/:id": {
            "put": {
                "description": "update agent photo profile by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "update agent photo profile",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "updateAvatar",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.UpdateAvatar"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.AccountUpdated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/redeem/callback": {
            "post": {
                "description": "callback for invoice xendit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "callback endpoint",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "invoiceCallback",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InvoiceCallback"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reward/:id": {
            "post": {
                "description": "create reward by admins.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reward"
                ],
                "summary": "admins can create reward",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "newReward",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.NewReward"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.RewardRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        },
        "/reward/:id/:rewardId": {
            "put": {
                "description": "update reward data by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reward"
                ],
                "summary": "update reward data",
                "parameters": [
                    {
                        "description": "body request",
                        "name": "updateReward",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateReward"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RewardRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            },
            "delete": {
                "description": "soft delete reward data by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reward"
                ],
                "summary": "soft delete reward data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RewardRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.Token": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.ClaimsReq": {
            "type": "object",
            "required": [
                "agent_id",
                "nota_img",
                "points",
                "product_id",
                "title"
            ],
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "nota_img": {
                    "type": "string"
                },
                "points": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.InvoiceCallback": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "merchant_name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.NewProduct": {
            "type": "object",
            "required": [
                "admin_id",
                "points",
                "title"
            ],
            "properties": {
                "admin_id": {
                    "type": "string"
                },
                "img": {
                    "type": "string"
                },
                "points": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.NewReward": {
            "type": "object",
            "required": [
                "admin_id",
                "category",
                "points",
                "title",
                "value"
            ],
            "properties": {
                "admin_id": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "img": {
                    "type": "string"
                },
                "points": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "dto.ProductRes": {
            "type": "object",
            "properties": {
                "rows_affected": {
                    "type": "integer"
                }
            }
        },
        "dto.Profile": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "admin_id": {
                    "type": "string"
                },
                "created_at": {
                    "description": "Transactions []_transaction.Domain ` + "`" + `json:\"transactions\"` + "`" + `",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "img": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "points": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.RedeemReq": {
            "type": "object",
            "required": [
                "agent_id",
                "points",
                "redeem_desc",
                "reward_id",
                "title"
            ],
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "points": {
                    "type": "integer"
                },
                "redeem_desc": {
                    "type": "string"
                },
                "reward_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.RewardRes": {
            "type": "object",
            "properties": {
                "rows_affected": {
                    "type": "integer"
                }
            }
        },
        "dto.TransactionRes": {
            "type": "object",
            "properties": {
                "rows_affected": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateAgentByAdmin": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateClaimsReq": {
            "type": "object",
            "required": [
                "id",
                "status"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateProduct": {
            "type": "object",
            "required": [
                "points",
                "title"
            ],
            "properties": {
                "img": {
                    "type": "string"
                },
                "points": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateReward": {
            "type": "object",
            "required": [
                "category",
                "points",
                "title",
                "value"
            ],
            "properties": {
                "category": {
                    "type": "string"
                },
                "img": {
                    "type": "string"
                },
                "points": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_admins_dto.AccountCreated": {
            "type": "object",
            "properties": {
                "rows_affected": {
                    "type": "integer"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_admins_dto.AccountUpdated": {
            "type": "object",
            "properties": {
                "rows_affected": {
                    "type": "integer"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_admins_dto.SignInReq": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_admins_dto.SignUpReq": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "img": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_admins_dto.UpdateAccount": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_admins_dto.UpdateAvatar": {
            "type": "object",
            "required": [
                "img"
            ],
            "properties": {
                "img": {
                    "type": "string"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_agents_dto.AccountCreated": {
            "type": "object",
            "properties": {
                "rows_affected": {
                    "type": "integer"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_agents_dto.AccountUpdated": {
            "type": "object",
            "properties": {
                "rows_affected": {
                    "type": "integer"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_agents_dto.SignInReq": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_agents_dto.SignUpReq": {
            "type": "object",
            "required": [
                "admin_id",
                "email",
                "name",
                "password"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "admin_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "img": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_agents_dto.UpdateAccount": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github.com_yossdev_mypoints-rest-api_src_agents_dto.UpdateAvatar": {
            "type": "object",
            "required": [
                "img"
            ],
            "properties": {
                "img": {
                    "type": "string"
                }
            }
        },
        "web.ErrorResp": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "server.mypoints.site",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "MyPoints API",
	Description: "This is an auto-generated API Docs.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
