basePath: /api/v1
definitions:
  auth.Token:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.ClaimsReq:
    properties:
      agent_id:
        type: string
      nota_img:
        type: string
      points:
        type: integer
      product_id:
        type: integer
      title:
        type: string
    required:
    - agent_id
    - nota_img
    - points
    - product_id
    - title
    type: object
  dto.NewProduct:
    properties:
      admin_id:
        type: string
      img:
        type: string
      points:
        type: integer
      title:
        type: string
    required:
    - admin_id
    - points
    - title
    type: object
  dto.NewReward:
    properties:
      admin_id:
        type: string
      img:
        type: string
      points:
        type: integer
      title:
        type: string
      value:
        type: integer
    required:
    - admin_id
    - points
    - title
    - value
    type: object
  dto.ProductRes:
    properties:
      rows_affected:
        type: integer
    type: object
  dto.Profile:
    properties:
      active:
        type: boolean
      admin_id:
        type: string
      created_at:
        description: Transactions []_transaction.Domain `json:"transactions"`
        type: string
      email:
        type: string
      id:
        type: string
      img:
        type: string
      name:
        type: string
      points:
        type: integer
      updated_at:
        type: string
    type: object
  dto.RedeemReq:
    properties:
      agent_id:
        type: string
      points:
        type: integer
      redeem_desc:
        type: string
      reward_id:
        type: integer
      title:
        type: string
    required:
    - agent_id
    - points
    - redeem_desc
    - reward_id
    - title
    type: object
  dto.RewardRes:
    properties:
      rows_affected:
        type: integer
    type: object
  dto.TransactionRes:
    properties:
      rows_affected:
        type: integer
    type: object
  dto.UpdateClaimsReq:
    properties:
      id:
        type: string
      status:
        type: string
    required:
    - id
    - status
    type: object
  dto.UpdateProduct:
    properties:
      img:
        type: string
      points:
        type: integer
      title:
        type: string
    required:
    - points
    - title
    type: object
  dto.UpdateReward:
    properties:
      img:
        type: string
      points:
        type: integer
      title:
        type: string
      value:
        type: integer
    required:
    - points
    - title
    - value
    type: object
  github.com_yossdev_mypoints-rest-api_src_admins_dto.AccountCreated:
    properties:
      rows_affected:
        type: integer
    type: object
  github.com_yossdev_mypoints-rest-api_src_admins_dto.AccountUpdated:
    properties:
      rows_affected:
        type: integer
    type: object
  github.com_yossdev_mypoints-rest-api_src_admins_dto.SignInReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  github.com_yossdev_mypoints-rest-api_src_admins_dto.SignUpReq:
    properties:
      email:
        type: string
      img:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  github.com_yossdev_mypoints-rest-api_src_admins_dto.UpdateAccount:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    type: object
  github.com_yossdev_mypoints-rest-api_src_admins_dto.UpdateAvatar:
    properties:
      img:
        type: string
    required:
    - img
    type: object
  github.com_yossdev_mypoints-rest-api_src_agents_dto.AccountCreated:
    properties:
      rows_affected:
        type: integer
    type: object
  github.com_yossdev_mypoints-rest-api_src_agents_dto.AccountUpdated:
    properties:
      rows_affected:
        type: integer
    type: object
  github.com_yossdev_mypoints-rest-api_src_agents_dto.SignInReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  github.com_yossdev_mypoints-rest-api_src_agents_dto.SignUpReq:
    properties:
      active:
        type: boolean
      admin_id:
        type: string
      email:
        type: string
      img:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - admin_id
    - email
    - name
    - password
    type: object
  github.com_yossdev_mypoints-rest-api_src_agents_dto.UpdateAccount:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    type: object
  github.com_yossdev_mypoints-rest-api_src_agents_dto.UpdateAvatar:
    properties:
      img:
        type: string
    required:
    - img
    type: object
host: server.mypoints.site
info:
  contact:
    email: zenhanprogram@gmail.com
    name: MyPoints Team Support
  description: This is an auto-generated API Docs.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://swagger.io/terms/
  title: MyPoints API
  version: "1.0"
paths:
  /:id/agent:
    post:
      consumes:
      - application/json
      description: create agent account by admins.
      parameters:
      - description: body request
        in: body
        name: signUp
        required: true
        schema:
          $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.SignUpReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.AccountCreated'
      summary: admins can create agent account with this api
      tags:
      - Agent
  /:id/transactions/claims:
    post:
      consumes:
      - application/json
      description: create claims transaction by agents.
      parameters:
      - description: body request
        in: body
        name: newClaims
        required: true
        schema:
          $ref: '#/definitions/dto.ClaimsReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.TransactionRes'
      summary: agent can create claims transaction
      tags:
      - Transaction
  /:id/transactions/redeem:
    post:
      consumes:
      - application/json
      description: create redeem transaction by agents.
      parameters:
      - description: body request
        in: body
        name: newRedeem
        required: true
        schema:
          $ref: '#/definitions/dto.RedeemReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.TransactionRes'
      summary: agent can create redeem transaction
      tags:
      - Transaction
  /admin/:id/transactions/claims/:transactionId:
    put:
      consumes:
      - application/json
      description: update claims transaction status by admins.
      parameters:
      - description: body request
        in: body
        name: updateClaims
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateClaimsReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TransactionRes'
      summary: admins can update claims transaction from agent
      tags:
      - Transaction
  /admin/login:
    post:
      consumes:
      - application/json
      description: check admins by checking given email and password.
      parameters:
      - description: body request
        in: body
        name: signIn
        required: true
        schema:
          $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.SignInReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Token'
      summary: check admins by given email return jwt token if successfully signIn
      tags:
      - Admin
  /admin/profile/:id:
    put:
      consumes:
      - application/json
      description: update admin data by id.
      parameters:
      - description: body request
        in: body
        name: updateAccount
        required: true
        schema:
          $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.UpdateAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.AccountUpdated'
      summary: update admin data
      tags:
      - Admin
  /admin/profile/avatar/:id:
    put:
      consumes:
      - application/json
      description: update admin photo profile by id.
      parameters:
      - description: body request
        in: body
        name: updateAvatar
        required: true
        schema:
          $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.UpdateAvatar'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.AccountUpdated'
      summary: update admin photo profile
      tags:
      - Admin
  /admin/signup:
    post:
      consumes:
      - application/json
      description: create admin account.
      parameters:
      - description: body request
        in: body
        name: signUp
        required: true
        schema:
          $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.SignUpReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_admins_dto.AccountCreated'
      summary: admins can create from register page
      tags:
      - Admin
  /login:
    post:
      consumes:
      - application/json
      description: check agent by checking given email and password.
      parameters:
      - description: body request
        in: body
        name: signIn
        required: true
        schema:
          $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.SignInReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Token'
      summary: check agent by given email return jwt token if successfully signIn
      tags:
      - Agent
  /product/:id:
    post:
      consumes:
      - application/json
      description: create product by admins.
      parameters:
      - description: body request
        in: body
        name: newProduct
        required: true
        schema:
          $ref: '#/definitions/dto.NewProduct'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ProductRes'
      summary: admins can create product
      tags:
      - Product
  /product/:id/:productId:
    delete:
      consumes:
      - application/json
      description: soft delete product data by id.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ProductRes'
      summary: soft delete product data
      tags:
      - Product
    put:
      consumes:
      - application/json
      description: update product data by id.
      parameters:
      - description: body request
        in: body
        name: updateProduct
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateProduct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ProductRes'
      summary: update product data
      tags:
      - Product
  /profile/:id:
    get:
      consumes:
      - application/json
      description: Get agent data by id.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Profile'
      summary: get agent data
      tags:
      - Agent
    put:
      consumes:
      - application/json
      description: update agent data by id.
      parameters:
      - description: body request
        in: body
        name: updateAccount
        required: true
        schema:
          $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.UpdateAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.AccountUpdated'
      summary: update agent data
      tags:
      - Agent
  /profile/avatar/:id:
    put:
      consumes:
      - application/json
      description: update agent photo profile by id.
      parameters:
      - description: body request
        in: body
        name: updateAvatar
        required: true
        schema:
          $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.UpdateAvatar'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.com_yossdev_mypoints-rest-api_src_agents_dto.AccountUpdated'
      summary: update agent photo profile
      tags:
      - Agent
  /reward/:id:
    post:
      consumes:
      - application/json
      description: create reward by admins.
      parameters:
      - description: body request
        in: body
        name: newReward
        required: true
        schema:
          $ref: '#/definitions/dto.NewReward'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.RewardRes'
      summary: admins can create reward
      tags:
      - Reward
  /reward/:id/:rewardId:
    delete:
      consumes:
      - application/json
      description: soft delete reward data by id.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RewardRes'
      summary: soft delete reward data
      tags:
      - Reward
    put:
      consumes:
      - application/json
      description: update reward data by id.
      parameters:
      - description: body request
        in: body
        name: updateReward
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateReward'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RewardRes'
      summary: update reward data
      tags:
      - Reward
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
